version: "3.4"

services:
  grpc-api:
    image: deephaven-examples/redpanda_dxfeed_financial_data-grpc-api:latest
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx4g -Ddeephaven.console.type=python -Ddeephaven.application.dir=/app.d
    depends_on:
        - redpanda

  prometheus:
    image: prom/prometheus
