version: "3.4"

services:
  redpanda:
      command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      image: docker.vectorized.io/vectorized/redpanda:latest
      ports:
      - 9092:9092
      - 29092:29092

  server:
    image: redpanda-dxfeed-financial-data/dx-server:latest
    environment:
      JAVA_TOOL_OPTIONS: -Xmx6g -Ddeephaven.console.type=python -Ddeephaven.application.dir=/data/app.d
    depends_on:
        - redpanda
    expose:
      - '8080'
    volumes:
      - ./data:/data
      - ./data/notebooks:/data/notebooks
      - api-cache:/cache

  web:
    image: redpanda-dxfeed-financial-data/dx-web:latest
    environment:
      JAVA_TOOL_OPTIONS: -Xmx4g
    expose:
      - '80'
    volumes:
      - ./data:/data
      - ./data/layouts:/data/layouts
      - ./data/notebooks:/data/notebooks
      - web-tmp:/tmp

  grpc-proxy:
    image: ghcr.io/deephaven/grpc-proxy:0.7.0
    environment:
      - BACKEND_ADDR=server:8080
    depends_on:
      server:
        condition: service_healthy
    expose:
      - '8080'

  envoy:
    image: ghcr.io/deephaven/envoy:0.7.0
    depends_on:
      server:
        condition: service_healthy
      grpc-proxy:
        condition: service_started
      web:
        condition: service_started
    ports:
      - "${PORT:-10000}:10000"

  dxfeed-trade:
    image: redpanda-dxfeed-financial-data/dxfeed-publish-trade:latest
    depends_on:
      server:
        condition: service_healthy
      grpc-proxy:
        condition: service_started
      web:
        condition: service_started

  dxfeed-quote:
    image: redpanda-dxfeed-financial-data/dxfeed-publish-quote:latest

  dxfeed-candle:
    image: redpanda-dxfeed-financial-data/dxfeed-publish-candle:latest

  dxfeed-profile:
    image: redpanda-dxfeed-financial-data/dxfeed-publish-profile:latest

  dxfeed-summary:
    image: redpanda-dxfeed-financial-data/dxfeed-publish-summary:latest

  dxfeed-order:
    image: redpanda-dxfeed-financial-data/dxfeed-publish-order:latest

  dxfeed-underlying:
    image: redpanda-dxfeed-financial-data/dxfeed-publish-underlying:latest

  dxfeed-timeandsale:
    image: redpanda-dxfeed-financial-data/dxfeed-publish-timeandsale:latest

  dxfeed-series:
    image: redpanda-dxfeed-financial-data/dxfeed-publish-series:latest

volumes:
    web-tmp:
    api-cache:
