name: Build

on:
  schedule:
    # Every day at 9AM EST
    - cron:  '0 13 * * *'
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
           docker build --target dx-server -t redpanda-dxfeed-financial-data/dx-server .
           docker build --target dx-web -t redpanda-dxfeed-financial-data/dx-web:latest .
           docker build --target dxfeed-publish-trade -t redpanda-dxfeed-financial-data/dxfeed-publish-trade:latest .
           docker build --target dxfeed-publish-quote -t redpanda-dxfeed-financial-data/dxfeed-publish-quote:latest .
           docker build --target dxfeed-publish-candle -t redpanda-dxfeed-financial-data/dxfeed-publish-candle:latest .
           docker build --target dxfeed-publish-profile -t redpanda-dxfeed-financial-data/dxfeed-publish-profile:latest .
           docker build --target dxfeed-publish-summary -t redpanda-dxfeed-financial-data/dxfeed-publish-summary:latest .
           docker build --target dxfeed-publish-order -t redpanda-dxfeed-financial-data/dxfeed-publish-order:latest .
           docker build --target dxfeed-publish-underlying -t redpanda-dxfeed-financial-data/dxfeed-publish-underlying:latest .
           docker build --target dxfeed-publish-timeandsale -t redpanda-dxfeed-financial-data/dxfeed-publish-timeandsale:latest .
           docker build --target dxfeed-publish-series -t redpanda-dxfeed-financial-data/dxfeed-publish-series:latest .
           docker-compose -f docker-compose.yml -p test-tables up -d

      - name: Validate tables
        uses: deephaven/action-assert-dh-tables-present@v1
        with:
          table-names: trades,quotes,candle,profile,summary,order,underlying,timeAndSale,series
          host: localhost
          max-retries: 10


      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.15.0
        id: notify-slack
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_DEVREL }}
        with:
          payload: '{"repository": "${{ github.repository }}", "message": "${{ github.workflow }}/${{ github.job }} failure", "link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
